<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.postchain</groupId>
        <artifactId>custom-sql-query-extension</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>custom-sql-query-image</artifactId>

    <dependencies>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>custom-sql-query-gtxmodule</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>
                            registry.gitlab.com/chromaway/postchain-chromia/chromaway/chromia-subnode:3.22.3@sha256:700c7e8139f0446b797ea97c29fbd3f3233f5c8094112150324ffc6ceb33136d
                        </image>
                    </from>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <entrypoint>INHERIT</entrypoint>
                        <creationTime>${git.commit.time}</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>docker-push</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <phase>deploy</phase>
                                    <goals>
                                        <goal>build</goal>
                                    </goals>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <architecture>amd64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                                <platform>
                                                    <architecture>arm64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                            </platforms>
                                        </from>
                                        <to>
                                            <image>${gitlab.registry}/${image.name}:${project.version}</image>
                                            <auth>
                                                <username>${env.CI_REGISTRY_USER}</username>
                                                <password>${env.CI_REGISTRY_PASSWORD}</password>
                                            </auth>
                                        </to>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>
</project>
